# Generated by Django 4.2.6 on 2023-10-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments_app', '0002_alter_assignment_id_alter_developer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='developer',
            old_name='assignments',
            new_name='assignments_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='assignment',
            new_name='assignment_id',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='developer',
            new_name='developer_id',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='assignment',
            new_name='assignment_id',
        ),
    ]
